#!/bin/bash

#location of Nnessy executable
Nnessy=

#location of Porter executable
Porter=

#$usage is runhybrid <input fasta> <output location>

numthreads=4

$Nnessy -i $1 -o $2 -n $numthreads
outseq=${2}/${1}.probs
python3 nnessyaccest.py ${outseq} ${outseq}_i 3state > nnessyestimate.txt
python3 nnessyaccest.py ${outseq} ${outseq}_i 8state > nnessy8estimate.txt

threeest=$(tail -n +2 nnessyestimate.txt)
eightest=$(tail -n +2 nnessy8estimate.txt)
threshold=0.8

if (( $threeest > $threshold )); then
    cat $2/${1}.ss > $2/${1}.hybridss
else
    Porter -i $1 --cpu $numthreads
    cat $1.ss3 > $2/${1}.hybridss
fi

if (( $eightest > $threshold )); then
    cat $2/${1}.ss8 > $2/${1}.hybridss8
else
    Porter -i $1 --cpu $numthreads
    cat $1.ss8 > $2/${1}.hybridss8
fi


